apiVersion: v1
kind: Service
metadata:
  labels:
    app: sanux
  name: svc-sanux
  namespace: revoada
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sanux
  sessionAffinity: ClientIP
  type: ClusterIP
