apiVersion: v1
kind: Service
metadata:
  labels:
    app: sanux
  name: svc-sanux-lb
  namespace: revoada
spec:
  ports:
  - nodePort: 32333
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sanux
  sessionAffinity: None
  type: LoadBalancer

